const GET_STATIONS = '@@StationList/GET_STATIONS';
const REQUEST_STATION_SUCCESS = '@@StationList/REQUEST_STATION_SUCCESS';
const REQUEST_STATION_ERROR = '@@StationList/REQUEST_STATION_ERROR';
const SET_CURRENT_STATION = '@@StationList/SET_CURRENT_STATION';

export default {
  GET_STATIONS,
  REQUEST_STATION_SUCCESS,
  REQUEST_STATION_ERROR,
  SET_CURRENT_STATION
};
