const GET_NETWORK_LIST = '@@NetworkModule/GET_NETWORK_LIST';
const REQUEST_NETWORKS_SUCCESS = '@@NetworkModule/REQUEST_NETWORKS_SUCCESS';
const REQUEST_NETWORKS_ERROR = '@@NetworkModule/REQUEST_NETWORKS_ERROR';

export default {
  GET_NETWORK_LIST,
  REQUEST_NETWORKS_SUCCESS,
  REQUEST_NETWORKS_ERROR
};
